[package]
name = "ray-rust"
version = "0.1.0"
authors = ["msakuta <masahiro.sakuta@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.22.1"
crossbeam = "0.7.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
