version: 2
jobs:
  build:
    docker:
      - image: rust:latest

    steps:
      - checkout

      - run:
          name: Cargo build
          command: cargo build

      - run:
          name: Cargo test
          command: cargo test

      - run:
          name: Cargo clippy
          command:
            rustup component add clippy --toolchain 1.43.1-x86_64-unknown-linux-gnu
            cargo clippy
